# Generated by Django 5.1.7 on 2025-03-17 08:09

import _user.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=_user.helpers.avatar_image_path),
        ),
    ]
