# Generated by Django 5.1.7 on 2025-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='incorrect_password_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lock_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
