# Generated by Django 5.1.7 on 2025-03-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_user_incorrect_password_count_user_lock_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lock_to',
            new_name='locked_to',
        ),
    ]
